WebApplication1/Controllers/ReviewController.cs
using BookPortal.Models;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web.Mvc;

namespace BookPortal.Controllers
{
	public class ReviewController : Controller
	{
		private readonly RevDBEntities db = new RevDBEntities();

		// GET: Review
		[HttpGet]
		public ActionResult Index()
		{
			ViewBag.BookName = "";
			ViewBag.AuthorName = "";
			ViewBag.Category = "";
			IQueryable<Review> reviews = db.Reviews.Include(a => a.AuthorName);
			return View(db.Reviews.ToList());
			//return View(reviews.ToList());
		}

		[HttpGet]
		public ActionResult SearchIndex(int page = 1, string sort = "BookName", string sortdir = "asc", string search = "")
		{
			int pageSize = 10;
			if (page < 1)
			{
				page = 1;
			}

			int skip = (page * pageSize) - pageSize;
			List<Review> data = GetReviews(search, sort, sortdir, skip, pageSize, out int totalRecord);
			ViewBag.TotalRows = totalRecord;
			return View(data);
		}


		[HttpPost]
		public ActionResult Index(string bookName, string authorName, string category, Review rev)
		{
			IEnumerable<Review> reviews = db.Reviews.ToList().Where(r => r.BookName.StartsWith(bookName) && r.AuthorName.StartsWith(authorName) && r.Category.StartsWith(category));
			return View(reviews);
		}

		public List<Review> GetReviews(string search, string sort, string sortdir, int skip, int pageSize, out int totalRecord)
		{
			IQueryable<Review> v = (from a in db.Reviews
									where
									   a.BookName.Contains(search) ||
									   a.AuthorName.Contains(search) ||
									   a.Category.Contains(search)
									select a
					 );
			totalRecord = v.Count();
			v = v.OrderBy(sort + " " + sortdir);
			if (pageSize > 0)
			{
				v = v.Skip(skip).Take(pageSize);
			}
			return v.ToList();
		}


		// GET: Review/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Review review = db.Reviews.Find(id);
			if (review == null)
			{
				return HttpNotFound();
			}
			return View(review);
		}

		// GET: Review/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Review/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "ReviewId,Category,BookName,ReviewType,BookSubject,BookAnalysis,AuthorName,OtherBooks,DateCreated")] Review review)
		{
			if (ModelState.IsValid)
			{
				db.Reviews.Add(review);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(review);
		}

		// GET: Review/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Review review = db.Reviews.Find(id);
			if (review == null)
			{
				return HttpNotFound();
			}
			return View(review);
		}

		// POST: Review/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ReviewId,Category,BookName,ReviewType,BookSubject,BookAnalysis,AuthorName,OtherBooks,DateCreated")] Review review)
		{
			if (ModelState.IsValid)
			{
				db.Entry(review).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(review);
		}

		// GET: Review/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Review review = db.Reviews.Find(id);
			if (review == null)
			{
				return HttpNotFound();
			}
			return View(review);
		}

		// POST: Review/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Review review = db.Reviews.Find(id);
			db.Reviews.Remove(review);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

WebApplication1/Views/Shared/_Carousel.cshtml
<div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('../../img/slide/slide1.png');"></div>
            <div class="carousel-caption">
                <h2>Newest Book Review</h2>
                <div class="col-md-12">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <a href="/Home/LastFiveReviews" class="button">SEE LIST VERSION</a>
                    </div>
                    <div class="col-md-4">
                        <a href="/ReviewVisualApperance/NewestBook" class="button">SEE VISUAL VERSION</a>
                    </div>
                    <div class="col-md-2"></div>
                </div>                
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../img/slide/slide2.png');"></div>
            <div class="carousel-caption">
                <h2>Popular Book Review</h2>
                <div class="col-md-12">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <a href="/Home/TopReviews" class="button">SEE LIST VERSION</a>
                    </div>
                    <div class="col-md-4">
                        <a href="/ReviewVisualApperance/PopularBook" class="button">SEE VISUAL VERSION</a>
                    </div>
                    <div class="col-md-2"></div>
                </div>                              
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../img/slide/slide3.png');"></div>
            <div class="carousel-caption">
                <h2>Oldest Book Review</h2>
                <div class="col-md-12">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <a href="/Home/FirstFiveReviews" class="button">SEE LIST VERSION</a>
                    </div>
                    <div class="col-md-4">
                        <a href="/ReviewVisualApperance/OldestBook" class="button">SEE VISUAL VERSION</a>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <i class="fa fa-angle-left"></i>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <i class="fa fa-angle-right"></i>
    </a>
</div>

WebApplication1/Views/Shared/_CategoryMenu.cshtml
@using BookPortal.Models;

@model  List<Categories>

<div class="list-group">

    @foreach (var item in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@item.CategoryName</a>
    }

</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="BookPortal">
    <meta name="author" content="Tolga&Ensar">
    <title>BookPortal</title>
    <!-- font-awesome -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if IE 7]>
    <link href="css/font-awesome-ie7.css" rel="stylesheet">
    <![endif]-->
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/css/form.css" rel="stylesheet" />
    <link href="~/css/addingReviewCss/form.css" rel="stylesheet" />
    <link href="~/css/addingReviewCss/webForm.css" rel="stylesheet" />
    <link href="~/css/addingReviewCss/util.css" rel="stylesheet" />
    <link href="~/css/tab.css" rel="stylesheet" />
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- custom CSS -->
    <link href="~/css/style.css" rel="stylesheet">
    <!--[if lte IE 8]>
    <link href="css/ie8.css" rel="stylesheet">
    <![endif]-->
    <!--[if lte IE 7]>
    <link href="css/ie7.css" rel="stylesheet">
    <![endif]-->
    <!-- JavaScript -->
    <script type="text/javascript" src="~/js/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.js"></script>
    <script type="text/javascript" src="~/js/plugins.js"></script>
    <script type="text/javascript" src="~/js/tab.js"></script>
    <script src="~/Scripts/jquery.shorten.min.js"></script>
    <script src="~/Scripts/jquery.shorten.js"></script>
    <!--[if lte IE 7]>
    <script type="text/javascript" src="js/boxsizing/jquery.boxsizing.js"></script>
    <![endif]-->
    <script type="text/javascript" src="~/js/bookp.js"></script>
</head>

<body>

    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Book Portal</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Reviews <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="/ReviewVisualApperance/Index">Visual Review Portal</a></li>
                            <li><a href="/Review/Index">List Review Portal</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Search", "SearchIndex", "Review")</li>
                    <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                </ul>
			</div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
    
    @RenderBody()
    <hr />

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <a class="footer-brand" href="/">BookPortal</a>
                    <p>Welcome to our Portal!</p>                   
                </div>
                <div class="col-lg-3 col-md-3">
                    <h3>CONTACT</h3>
                    <address>
                        <i class="fa fa-map-marker"></i> Bahcesehir University<br>
                        <i class="fa fa-phone"></i> (212) 570 00 00<br>
                        <i class="fa fa-envelope"></i> info@bahcesehir.com
                    </address>
                </div>
                <div class="col-lg-3 col-md-3">
                    <h3>LATEST TWEETS</h3>
                    <ul class="latest-tweets">
                        <li>
                            <i class="fab fa-twitter-square"></i> Most current book reviews here!
                        </li>
                        <li>
                            <i class="fab fa-twitter-square"></i> Most popular book reviews here!
                        </li>
                    </ul>
                </div>               
            </div><!-- /.row -->
        </div><!-- /.container -->
    </footer>
    <div class="footer-after">
        <div class="container">
            <div class="row">
                <p class="col-md-10">©2019 All rights reserved.</p>               
            </div><!-- /.row -->
        </div>
    </div>
</body>
</html>

WebApplication1/Views/Shared/_RecentProjects.cshtml
<div class="section" id="recent-projects" style="position: relative;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-title">Popular Categories</h2>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="/Home/CategoryScienceFiction" class="link-book_archive">
                    <div class="overlay-book_archive">
                        <h3>Science Fiction Book Reviews</h3>
                        <small class="text-muted">
                            Click to the image to read the reviews of Science Fiction books.
                        </small>
                    </div><!-- /.overlay-book_archive -->
                    <img class="img-responsive img-home-book_archive" src="~/img/book_archive_1.png" alt="book_archive 1" onclick="@("window.location.href='" + @Url.Action("CategoryScienceFiction", "Home") + "'")">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="/Home/CategoryGuide" class="link-book_archive">
                    <div class="overlay-book_archive">
						<h3>Guide Book Reviews</h3>
						<small class="text-muted">
							Click to the image to read the reviews of Guide books.
						</small>
                    </div><!-- /.overlay-book_archive -->
                    <img class="img-responsive img-home-book_archive" src="~/img/book_archive_2.png" alt="book_archive 2">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="/Home/CategoryDiaries" class="link-book_archive">
                    <div class="overlay-book_archive">
						<h3>Diary Book Reviews</h3>
						<small class="text-muted">
							Click to the image to read the reviews of Diary books.
						</small>
                    </div><!-- /.overlay-book_archive -->
                    <img class="img-responsive img-home-book_archive" src="~/img/book_archive_3.png" alt="book_archive 3">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="/Home/CategoryJournals" class="link-book_archive">
                    <div class="overlay-book_archive">
						<h3>Journal Book Reviews</h3>
						<small class="text-muted">
							Click to the image to read the reviews of Journal books.
						</small>
                    </div><!-- /.overlay-book_archive -->
                    <img class="img-responsive img-home-book_archive" src="~/img/book_archive_4.png" alt="book_archive 4">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="/Home/CategoryDrama" class="link-book_archive">
                    <div class="overlay-book_archive">
						<h3>Drama Book Reviews</h3>
						<small class="text-muted">
							Click to the image to read the reviews of Drama books.
						</small>
                    </div><!-- /.overlay-book_archive -->
                    <img class="img-responsive img-home-book_archive" src="~/img/book_archive_5.png" alt="book_archive 5">
                </a>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a href="/Home/CategoryArt" class="link-book_archive">
                    <div class="overlay-book_archive">
						<h3>Art Book Reviews</h3>
						<small class="text-muted">
							Click to the image to read the reviews of Art books.
						</small>
                    </div><!-- /.overlay-book_archive -->
                    <img class="img-responsive img-home-book_archive" src="~/img/book_archive_6.png" alt="book_archive 6">
                </a>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.section -->